/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbscheduler;

/**
 *
 * @author umang
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Starter extends javax.swing.JFrame {

    String UName;
/**
     * Creates new form Starter
     */
        String UDate;

    
    public Starter() 
    {
        this.UDate = null;
        this.UName = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Create = new javax.swing.JButton();
        Date = new javax.swing.JTextField();
        Close = new javax.swing.JButton();
        Name = new javax.swing.JTextField();

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signup");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\umang\\Downloads\\usecake.jpg")); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setText("+Create");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Date");

        Create.setBackground(new java.awt.Color(255, 0, 0));
        Create.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Create.setIcon(new javax.swing.ImageIcon("C:\\Users\\umang\\Downloads\\create.jpg")); // NOI18N
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Close.setBackground(new java.awt.Color(255, 0, 51));
        Close.setForeground(new java.awt.Color(255, 0, 0));
        Close.setIcon(new javax.swing.ImageIcon("C:\\Users\\umang\\OneDrive\\Pictures\\Screenshots\\Screenshot (33).png")); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Date)
                            .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Create, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(Create)
                .addGap(288, 288, 288))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(641, 382));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
    // TODO add your handling code here:
        
         try
         {
             this.dispose();
             new Init().setVisible(true);
             DBScheduler dbs = new DBScheduler();
             dbs.callScheduler();
         } catch(Exception e)
         {
             
         }
        if(Name.getText().length()==0)  // Checking for empty field
            JOptionPane.showMessageDialog(null, "Please fill up userID");
        else if(Date.getText().length()==0)  // Checking for empty field
            JOptionPane.showMessageDialog(null, "Please fill up Date");
        else
        {
          UName = Name.getText();   // Collecting the input
          UDate = Date.getText(); 
          
       // Collecting the input
       
       //String pwd = String.copyValueOf(pass);  // converting from array to string
       /*if(validate_login(UName,UDate))
          JOptionPane.showMessageDialog(null, "Correct Login Credentials");        
       else
          JOptionPane.showMessageDialog(null, "Incorrect Login Credentials");*/
       
     try{           
       Class.forName("org.sqlite.JDBC");  // MySQL database connection
       Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\Users\\umang\\OneDrive\\Documents\\NetBeansProjects\\BD.db" ); //+ "user= & password=");     
       PreparedStatement pst = conn.prepareStatement("insert into BD(Name,Date) values (?,?) ");
       pst.setString(1, Name.getText()); 
       pst.setString(2, Date.getText());
       //int rs;     
       
       if("/".equals(UDate.substring(2,3)) && "/".equals(UDate.substring(5,6)) && Integer.parseInt(UDate.substring(0,2))<=12 && Integer.parseInt(UDate.substring(0,2))>0 )
        {
           int month=Integer.parseInt(UDate.substring(0,2));
           int days=Integer.parseInt(UDate.substring(3,5));
           int year=Integer.parseInt(UDate.substring(6,10));
           System.out.println(month + "/" + days +"/" + year );
           switch(month)
           {
               case 1 :
               {
    
                   
                   if(days<=31 && days>0)
                   {
                       System.out.println(month + "/" + days +"/" + year );
                       pst.executeUpdate();
                   }
                         
                   else
                       JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   break;
               }
               case 2 :
               {
                   if(days==29)
                   {
                       if((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0))
                           pst.executeUpdate();
                       else
                           JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   }      
                   else if(days<=28 && days>0)
                        pst.executeUpdate();
                   else
                        JOptionPane.showMessageDialog(null, "Please set date  MM/DD/YYYY format correctly...."); 
                   break;
               }
               case 3 :
               {
                   if(days<=31 && days>0)
                         pst.executeUpdate();
                   else
                       JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   break;
               }
               case 4 :
               {
                   if(days<=30 && days>0)
                         pst.executeUpdate();
                   else
                       JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   break;
               }
               case 5 :
               {
                   if(days<=31 && days>0)
                         pst.executeUpdate();
                   else
                       JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   break;
               }
               case 6 :
               {
                   if(days<=30 && days>0)
                         pst.executeUpdate();
                   else
                       JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   break;
               }
               case 7 :
               {
                   if(days<=31 && days>0)
                         pst.executeUpdate();
                   else
                       JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   break;
               }
               case 8 :
               {
                   if(days<=31 && days>0)
                         pst.executeUpdate();
                   else
                       JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   break;
               }
               case 9 :
               {
                   if(days<=30 && days>0)
                         pst.executeUpdate();
                   else
                       JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   break;
               }
               case 10 :
               {
                   if(days<=31 && days>0)
                         pst.executeUpdate();
                   break;
               }
               case 11 :
               {
                   if(days<=30 && days>0)
                         pst.executeUpdate();
                   else
                       JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   break;
               }
               case 12 :
               {
                   if(days<=31 && days>0)
                         pst.executeUpdate();
                   else
                       JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   break;
               }
               default :
                   JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
                   //break;
                       
           }
       
         //JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
     //  pst.executeUpdate();
       //rs=pst.executeUpdate();
       //return rs.next();
       //return 1;
       
       //MainWindow my = new MainWindow();//UName,UDate);
      // this.dispose();
      // my.setVisible(true);
        
        }
       else
           JOptionPane.showMessageDialog(null, "Please set date in MM/DD/YYYY format correctly...."); 
           
    
   }
   catch(ClassNotFoundException | SQLException e){
       //return false;
   }
        
       
   }        

        
        
        
    }//GEN-LAST:event_CreateActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
         try
         {
             new Init().setVisible(true);
             DBScheduler dbs = new DBScheduler();
             dbs.callScheduler();
         }catch(Exception e)
         {
             
         }
         
    }//GEN-LAST:event_CloseActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Starter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        
        //</editor-fold>

        
        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Starter().setVisible(true);
            }
        });*/
    //}
    
    
   

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton Create;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

   /* private boolean validate_login(String UName,String UDate) {
  
   }      */ 
}
    

